### ISSUE TITLE
No Rviz

### ISSUE THREAD

**Issue by ThomHordijk** [atinfinity/jetson_ros_docker#1]
Hello I found this docker image while searching for a solution to use ros in a docker container on jetson agx xavier.

Jetpack 4.4

I assumed that this container should also be able to run Rviz however when I try this i get the following error:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-melodic'
[ INFO] [1591280331.668887423]: rviz version 1.13.12
[ INFO] [1591280331.669215214]: compiled against Qt version 5.9.5
[ INFO] [1591280331.669300018]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1591280331.705949593]: Forcing OpenGl version 0.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
rviz: /build/ogre-1.9-i02lBV/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLSupport.cpp:56: virtual void Ogre::GLSupport::initialiseExtensions(): Assertion `pcVer && "Problems getting GL version string using glGetString"' failed.
Aborted (core dumped)

```
Everything I can find in regard to the given errors does not seem to apply to my situation, so i was wondering if you had encoutered this error? Or was wrong in asssuming this docker should be able to run rviz on a jetson xavier?

**Comment by atinfinity** [comment]
@ThomHordijk Thank you for your report. I checked Jetson TX2(JetPack 4.3).

> [ INFO] [1591280331.705949593]: Forcing OpenGl version 0.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
rviz: /build/ogre-1.9-i02lBV/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLSupport.cpp:56: virtual void Ogre::GLSupport::initialiseExtensions(): Assertion `pcVer && "Problems getting GL version string using glGetString"' failed.
Aborted (core dumped)

I think that this error is due to graphics driver.

------

Could you please give me the folliwing information?

## Used branch
https://github.com/atinfinity/jetson_ros_docker has the following branch.

- master
- melodic
- kinetic

Which branch did you use?

## Operated command
I hope to know your operated command(docker build, docker run, rviz etc,,,)

**Comment by ThomHordijk** [comment]
Hi thank you for replying so quickly I used the master branch of this repository as the jetson uses L4T. 
I followed the commands in the read me. 

`docker build -t mydockertag .`
`./launch_container.sh`
`roscore`

in a different terminal
`docker container ls`
`docker exec -it [runningdockerid] bash`
`rviz`

I changed the docker images that the .sh executable looks for to correspond with my image name and i had to remove the `--runtime nvidia flag` this is as i understand it done automaticaly when nvidia-docker2 is installed. 

We found the problem I had to configure the /etc/docker/daemon.json
